arb-dir: lib/core/localization/l10n
template-arb-file: app_en.arb
output-localization-file: intl_l10n.dart
nullable-getter: false
untranslated-messages-file: untranslated_messages.json
synthetic-package: false
