name: jastipin_yuk
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gen: ^5.11.0
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  get_it: ^8.2.0
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  mask_text_input_formatter: ^2.9.0
  firebase_auth: ^6.0.0
  google_sign_in: ^7.1.1
  firebase_core: ^4.0.0
  fluentui_system_icons: ^1.1.273
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.0
  shimmer: ^3.0.0
  web_socket_channel: ^3.0.3
  rxdart: ^0.28.0
  pull_to_refresh: ^2.0.0
  hive: ^2.2.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
